name: CI

on:
  push:
  pull_request:

jobs:
  markdown:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: .markdownlint-cli2.yaml
          globs: |
            **/*.md

